[package]
name = "trust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html 

[lib]
name = "trust"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
tun-tap = "0.1.2"
pktparse = "0.7.1"
etherparse = "0.12.0"